"""add email otp verification

Revision ID: 2e7e38cd39cb
Revises: 7f5cbf3116f9
Create Date: 2026-08-24 14:16:38.324586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e7e38cd39cb'
down_revision: Union[str, Sequence[str], None] = '7f5cbf3116f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'users',
    sa.Column(
        'email_verified',
        sa.Boolean(),
        nullable=False,
        server_default=sa.false()
        )
    )
    op.add_column('users', sa.Column('otp_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('otp_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_expires_at')
    op.drop_column('users', 'otp_hash')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
