"""add_cascade_delete_to_relationships

Revision ID: 6694f13fc8bf
Revises: dac454a699ae
Create Date: 2026-08-26 10:12:41.630041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6694f13fc8bf'
down_revision: Union[str, Sequence[str], None] = 'dac454a699ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
