"""add thumbnail url to movies

Revision ID: 7f5cbf3116f9
Revises: bd83ec3402e9
Create Date: 2026-08-24 13:24:48.181240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f5cbf3116f9'
down_revision: Union[str, Sequence[str], None] = 'bd83ec3402e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'thumbnail_url')
    # ### end Alembic commands ###
