"""add showtime to reservation seats

Revision ID: 8a77f4e9f8e4
Revises: 7d93d9d7084f
Create Date: 2026-08-24 12:41:42.744880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a77f4e9f8e4'
down_revision: Union[str, Sequence[str], None] = '7d93d9d7084f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation_seats', sa.Column('showtime_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('uq_reservation_seat'), 'reservation_seats', type_='unique')
    op.create_unique_constraint('uq_showtime_seat', 'reservation_seats', ['showtime_id', 'seat_id'])
    op.create_foreign_key(None, 'reservation_seats', 'showtimes', ['showtime_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservation_seats', type_='foreignkey')
    op.drop_constraint('uq_showtime_seat', 'reservation_seats', type_='unique')
    op.create_unique_constraint(op.f('uq_reservation_seat'), 'reservation_seats', ['reservation_id', 'seat_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('reservation_seats', 'showtime_id')
    # ### end Alembic commands ###
