"""add showtime to reservation seats

Revision ID: bd83ec3402e9
Revises: 8a77f4e9f8e4
Create Date: 2026-08-24 12:46:14.209751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd83ec3402e9'
down_revision: Union[str, Sequence[str], None] = '8a77f4e9f8e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
